version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      SRV_HOST: "0.0.0.0"
      SRV_PORT: "8080"
      SRV_NUMBER_OF_TIMES_R_APPLIES_F: 8
      SRV_SIZE_OF_EACH_VALUE: 16
    ports:
      - '8080:8080'
    restart: 'no'

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      SRV_HOST: "server"
      SRV_PORT: "8080"
    restart: 'no'
    depends_on:
      - server
